<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Proposal - <?= htmlspecialchars($proposal['job_title']) ?></title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 700px; margin: 40px auto; color: #333; line-height: 1.7; }
        h1 { color: #1a3a5c; font-size: 1.4rem; border-bottom: 2px solid #2c5f8a; padding-bottom: 8px; }
        .meta { color: #666; font-size: 0.85rem; margin-bottom: 20px; }
        .content { white-space: pre-wrap; }
        .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #ddd; color: #888; font-size: 0.8rem; }
        @media print {
            body { margin: 20px; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom:20px;">
        <button onclick="window.print()" style="padding:8px 16px;background:#2c5f8a;color:#fff;border:none;border-radius:4px;cursor:pointer;">Print / Save as PDF</button>
        <a href="/proposals/view/<?= $proposal['id'] ?>" style="margin-left:10px;color:#2c5f8a;">Back to proposal</a>
    </div>

    <h1>Proposal: <?= htmlspecialchars($proposal['job_title']) ?></h1>
    <div class="meta">
        <?= htmlspecialchars($proposal['platform_name']) ?> &bull;
        <?= date('F j, Y', strtotime($proposal['created_at'])) ?> &bull;
        Version <?= $proposal['version'] ?>
        <?php if ($proposal['suggested_rate']): ?>
            &bull; Rate: $<?= number_format($proposal['suggested_rate'], 2) ?>
        <?php endif; ?>
    </div>

    <div class="content"><?= htmlspecialchars($proposal['content']) ?></div>

    <div class="footer">
        Generated by Freelance Proposal Optimizer &bull; <?= date('Y') ?>
    </div>
</body>
</html>
